info:
  component: account-service

server:
  port: 8372

spring:
  application:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8370/eureka/}
    registerWithEureka: true
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2