info:
  component: gateway-service

server:
  port: 8371

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8370/eureka/
    registerWithEureka: true

#logging:
#  level:
#    ROOT: INFO
#    org.springframework.web: DEBUG

zuul:
  prefix: /api
  routes:
    account:
      path: /account/**
      serviceId: account
    customer:
      path: /customer/**
      serviceId: customer